def get_hardcoded_toc():
    """
    Returns hardcoded table of contents structures for the 5 Icelandic Riding Levels books.
    Two maps: 'english' and 'icelandic'.
    Structure: dict[language: str -> level: int -> list[chapter: dict with 'num', 'name', 'subchapters': dict[str, int]]]
    Subchapters: dict[subchapter_name: str -> page_num: int] for easy page reference during iteration.
    Based on extracted TOC from PDFs.
    """
    return {
        1: [
            {
                "num": 1,
                "name": "Behavior, Instincts and Nature of Horses",
                "page": 4,
                "subchapters": {
                    "The horse is a herd animal.": 4,
                    "The flight instinct.": 6,
                    "Sight.": 6,
                    "Hearing.": 9,
                    "Smell.": 10,
                    "Taste.": 10,
                    "Touch.": 10,
                },
            },
            {
                "num": 2,
                "name": "The Horse's Body",
                "page": 11,
                "subchapters": {
                    "The body parts of the horse.": 12,
                },
            },
            {
                "num": 3,
                "name": "The Rider, Equipment and Safety",
                "page": 13,
                "subchapters": {},
            },
            {
                "num": 4,
                "name": "Handling of Horses",
                "page": 15,
                "subchapters": {
                    "Leadership.": 15,
                    "The stable and environment of the horse.": 16,
                    "Approaching a horse.": 17,
                    "Putting on the halter.": 19,
                    "Tying the horse.": 19,
                    "Grooming the horse.": 21,
                    "Cleaning the hooves.": 25,
                    "Setting the horse free.": 25,
                },
            },
            {
                "num": 5,
                "name": "Tacking up the Horse",
                "page": 27,
                "subchapters": {
                    "Mouth, bridle and bits.": 28,
                    "Bridling the horse.": 33,
                    "The saddle.": 35,
                    "Putting the saddle on the horse.": 39,
                    "Taking care of tack.": 41,
                },
            },
            {
                "num": 6,
                "name": "Leading the Horse",
                "page": 43,
                "subchapters": {"Leading the horse from the side.": 46},
            },
            {
                "num": 7,
                "name": "Mounting and Dismounting",
                "page": 48,
                "subchapters": {"Mounting.": 49, "Dismounting.": 51},
            },
            {
                "num": 8,
                "name": "The Gaits of the Icelandic Horse",
                "page": 52,
                "subchapters": {
                    "The gaits.": 52,
                    "Walk.": 53,
                    "Trot.": 54,
                    "Tölt.": 54,
                    "Pace.": 55,
                },
            },
            {
                "num": 9,
                "name": "Seat of the Rider",
                "page": 58,
                "subchapters": {
                    "The importance of a good seat.": 58,
                    "Breathing,": 60,
                    "Body posture, balance and concentration.": 60,
                    "The saddle influences the seat of the rider.": 61,
                    "The half-seat.": 61,
                    "The classical (basic) seat.": 63,
                    "The center of gravity in the classical seat.": 63,
                    "The rider's feet.": 64,
                    "The upper part of the body.": 65,
                    "Following the horse's movements.": 66,
                    "The light seat.": 66,
                    "Posting the trot.": 67,
                    "How to post": 68,
                    "Identifying the diagonals.": 68,
                    "Switching between the diagonals.": 69,
                    "The advantages of posting the trot.": 70,
                    "Faulty seat and problems.": 70,
                },
            },
            {
                "num": 10,
                "name": "Reins and Rein Hold",
                "page": 72,
                "subchapters": {
                    "Correct rein hold.": 73,
                    "Shortening the reins.": 74,
                    "Bringing the reins.": 74,
                },
            },
            {
                "num": 11,
                "name": "Lunging Exercises",
                "page": 76,
                "subchapters": {
                    "The balance of rider and horse.": 77,
                    "Lunging exercises.": 78,
                    "Safety and facilities.": 78,
                },
            },
            {
                "num": 12,
                "page": 85,
                "name": "When Leaving the Stable",
                "subchapters": {
                    "Riders skills when completing Level 1.": 86,
                    "The body parts of the horse.": 87,
                    "Index.": 88,
                },
            },
        ],
        2: [
            {
                "num": 1,
                "name": "Evolution of the Horse",
                "page": 4,
                "subchapters": {
                    "Eohippus.": 4,
                    "Climate and environmental changes.": 5,
                    "The horse/Equus.": 6,
                    "Przewalsky horse.": 6,
                },
            },
            {
                "num": 2,
                "name": "Icelandic Horse",
                "page": 8,
                "subchapters": {
                    "Historic background.": 8,
                    "Origin.": 8,
                    "Role and shaping factors.": 9,
                    "Characteristics and attributes.": 10,
                    "The official breeding goals for the Icelandic horse.": 11,
                    "The main role of the Icelandic horse.": 13,
                },
            },
            {
                "num": 3,
                "name": "The Attitudes of Humans and Horses",
                "page": 16,
                "subchapters": {
                    "The attitude of humans towards horses.": 16,
                    "Pressure, reaction, results (reward).": 17,
                    "Reading the physical signals of the horse.": 18,
                    "The character of horses.": 19,
                    "Memory and learning.": 20,
                    "Teaching from both sides.": 21,
                    "Concentration and focus.": 22,
                    "Rewards – the key to successful training.": 24,
                    "If things go wrong.": 25,
                    "The horse does not understand.": 26,
                    "The horse is scared.": 26,
                    "Physical reasons.": 26,
                    "The horse does not trust its trainer.": 26,
                    "Doing the right thing.": 26,
                    "Setting up positive situations.": 27,
                    "Setting up for success.": 28,
                },
            },
            {
                "num": 4,
                "name": "How does the horse learn the aids?",
                "page": 29,
                "subchapters": {
                    "How does the horse learn the aids?": 29,
                    "Use of aids.": 29,
                    "Types of aids.": 30,
                    "Weight aids.": 30,
                    "Leg aids.": 31,
                    "Aids given with the crop.": 32,
                    "Rein aids.": 33,
                    "The timing and strength of the aids.": 33,
                },
            },
            {
                "num": 5,
                "page": 35,
                "name": "Forward and Stop",
                "subchapters": {
                    "How to practice forward and stop.": 35,
                    "Forward and stop exercises.": 37,
                },
            },
            {
                "num": 6,
                "name": "Work-in-Hand",
                "page": 38,
                "subchapters": {
                    "Why work in hand?": 38,
                    "The crop.": 39,
                    "Bending the neck.": 40,
                    "How to perform the exercise.": 41,
                    "Common mistakes.": 42,
                    "One rein stop.": 43,
                    "Teaching the one-rein stop.": 43,
                    "Why one-rein stop?": 44,
                },
            },
            {
                "num": 7,
                "name": "The Riding Arena",
                "page": 45,
                "subchapters": {
                    "The riding arena.": 47,
                    "The figures of the arena.": 48,
                    "The rules of the arena.": 51,
                },
            },
            {
                "num": 8,
                "name": "Rein Holds and Rein Aids",
                "page": 52,
                "subchapters": {
                    "The prerequisites of a good rein-hold.": 52,
                    "Rein connection.": 53,
                    "Rein aids.": 54,
                    "Rein hold.": 55,
                    "Loose rein.": 56,
                    "Rein connection.": 57,
                    "On the bit.": 58,
                },
            },
            {
                "num": 9,
                "name": "Gait Transitions",
                "page": 59,
                "subchapters": {
                    "What is a gait transition?": 59,
                    "How is a gait transition ridden.": 59,
                    "Walk - trot or tölt - walk.": 59,
                    "Walk - trot - walk.": 59,
                },
            },
            {
                "num": 10,
                "name": "Training in the Open",
                "page": 61,
                "subchapters": {
                    "Training in the open.": 61,
                    "Natural hindrances.": 65,
                    "Guidelines to keep in mind.": 66,
                    "Riders skills at the completion of Level 2.": 68,
                },
            },
        ],
        4: [
            {
                "num": 1,
                "name": "The Rider",
                "subchapters": {
                    "The Emotional Wellness of the Rider.": 6,
                    "Riding is a Sport.": 8,
                    "Learning/Education.": 13,
                    "Flow.": 15,
                    "Focus.": 16,
                    "Self-talk/Self-discipline.": 18,
                    "Self-esteem/Self-discipline.": 19,
                    "Spiritual balance.": 20,
                    "Environment/Facilities.": 21,
                    "The physical well-being of the Rider.": 28,
                    "Balance/Strength/Coordination.": 31,
                    "Agility/Body awareness.": 33,
                    "Breath of the Rider.": 35,
                    "Physical Exercises for Riders.": 42,
                    "Stretches for Riders.": 49,
                },
            },
            {
                "num": 2,
                "name": "The Health of the Horse",
                "subchapters": {
                    "Accidents/Injuries.": 57,
                    "Worms.": 58,
                    "Lice.": 59,
                    "Colic.": 60,
                    "Urinary stone.": 62,
                    "Pasture laminitis.": 64,
                    "Spavin.": 66,
                    "Swelling of the suspensory ligament.": 67,
                },
            },
            {
                "num": 3,
                "name": "Legs - Mouth - Back",
                "subchapters": {
                    "Legs and leg construction of horses.": 69,
                    "Lower leg and hoof of the horse.": 72,
                    "The hoof.": 75,
                    "Shoeing the horse.": 78,
                    "The mouth of the horse.": 85,
                    "The back of the horse.": 89,
                },
            },
            {
                "num": 4,
                "name": "Tack and its use",
                "subchapters": {
                    "The Saddle.": 101,
                    "Bridles and nosebands.": 108,
                    "Nosebands.": 114,
                    "Shanks - The Icelandic Shank Bit.": 115,
                    "Reins.": 119,
                },
            },
            {
                "num": 5,
                "name": "Training Concepts - Training Levels",
                "subchapters": {
                    "Systematic Training.": 126,
                    "Psychological balance.": 130,
                    "Training levels.": 133,
                    "Even tempo - even steps.": 135,
                    "Contact - connection of the aids.": 138,
                    "Straight - suppleness of the aids.": 140,
                    "Flow of aids - flexible.": 142,
                    "Suspension - Thrust - Power.": 145,
                    "Collection/Round - Lightness.": 149,
                    "Speed.": 153,
                    "Hólar University Training Scale.": 155,
                },
            },
            {
                "num": 6,
                "name": "Exercises - Agility - Form",
                "subchapters": {
                    "Moving in and out on a circle.": 158,
                    "Leg yield - long rein.": 164,
                    "Shoulder in.": 169,
                    "The half-halt.": 175,
                    "Half-halt - topline.": 180,
                    "Walking backwards - Backing.": 183,
                    "Turn on long rein - circle rein.": 166,
                },
            },
        ],
        3: [
            {
                "num": 1,
                "name": "Feeding Horses",
                "page": 4,
                "subchapters": {
                    "Care and health.": 4,
                    "The digestive system.": 5,
                    "Mouth.": 6,
                    "Gullet.": 6,
                    "Stomach.": 7,
                    "Small intestine.": 7,
                    "Large intestine.": 8,
                    "Feeds; influence on the horse.": 8,
                    "The importance of forage.": 9,
                    "Evaluating grass/hay.": 9,
                    "Grains.": 11,
                    "Which horses need grains?": 11,
                    "Minerals and vitamins.": 11,
                    "Fat sources and influence.": 12,
                    "Health and condition.": 13,
                    "Conditioning scale.": 14,
                    "Nutritional needs.": 15,
                    "Summer.": 16,
                    "Fall.": 17,
                    "Winter.": 17,
                },
            },
            {
                "num": 2,
                "name": "Conformation and Movement",
                "page": 22,
                "subchapters": {
                    "The conformation of horses compared to humans.": 22,
                    "Aspects regarding conformation.": 23,
                    "Center of gravity.": 27,
                    "Official breeding goal for conformation.": 27,
                    "Movement and step.": 28,
                    "Form - Outline.": 29,
                    "Form and balance.": 30,
                    "The rider plays major role.": 32,
                },
            },
            {
                "num": 3,
                "name": "The Psychical Balance of the Horse",
                "page": 35,
                "subchapters": {
                    "Tension and willingness.": 35,
                    "The calm horse.": 35,
                    "Characteristics and causes of tension.": 36,
                    "Tension can be physical and/or physiological.": 37,
                },
            },
            {
                "num": 4,
                "name": "The Gaits of the Icelandic Horse",
                "page": 40,
                "subchapters": {
                    "Movement and gaits.": 40,
                    "Walk.": 41,
                    "Riding the horse in walk.": 41,
                    "The sequence of walk.": 42,
                    "Trot.": 44,
                    "Riding the trot.": 44,
                    "Faulty trot.": 46,
                    "Tölt.": 47,
                    "Riding tölt.": 47,
                    "Pacy tölt and trotty tölt.": 49,
                    "Riding the canter.": 50,
                    "Pace.": 53,
                    "Riding pace.": 53,
                },
            },
            {
                "num": 5,
                "name": "Training Horses",
                "page": 55,
                "subchapters": {
                    "Speed, direction, and gait.": 55,
                    "Forward thinking.": 56,
                    "Systematic training.": 57,
                    "Unevenness (crookedness).": 59,
                    "Causes of unevenness.": 59,
                    "The symptoms of unevenness.": 60,
                    "The influence of unevenness on gaits.": 62,
                    "Minimizing unevenness on gaits.": 63,
                    "Classical training.": 63,
                },
            },
            {
                "num": 6,
                "name": "Leg Yield and Circle Work",
                "page": 64,
                "subchapters": {
                    "Yielding the hindquarters.": 64,
                    "Yielding from the leg.": 65,
                    "Working on the circle.": 66,
                    "Flexing and bending.": 67,
                    "Why bend the horse?": 68,
                    "What is a circle?": 68,
                    "Left/right seat.": 68,
                    "Riding circles and serpentines.": 70,
                    "Problems when riding on the circle.": 71,
                    "Yielding on the circle.": 73,
                },
            },
            {
                "num": 7,
                "name": "Turn on the Forehand and Leg Yield",
                "page": 75,
                "subchapters": {
                    "What is a turn on the forehand?": 75,
                    "Riding the turn on the forehand.": 76,
                    "Leg yield.": 77,
                    "Leg yield exercises.": 79,
                },
            },
            {
                "num": 8,
                "name": "Canter Training",
                "page": 80,
                "subchapters": {
                    "Canter training.": 80,
                    "The importance of facilities and environment.": 81,
                    "Beginning of canter training.": 81,
                    "Problems in canter.": 84,
                },
            },
            {
                "num": 9,
                "name": "Beginning Tölt Training",
                "page": 86,
                "subchapters": {"Walk - tölt - walk.": 86, "Riding tölt.": 89},
            },
            {
                "num": 10,
                "name": "Cavalletti (Training Poles) and Jumping",
                "page": 91,
                "subchapters": {
                    "The rider.": 92,
                    "Seat and balance.": 94,
                    "Training poles (cavalletti).": 95,
                    "Jumps.": 96,
                },
            },
            {
                "num": 11,
                "page": 103,
                "name": "Riders skills when finishing Level 1.",
                "subchapters": {"Theory.": 103, "Practice.": 103},
            },
        ],
        4: [
            {
                "num": 1,
                "name": "The Rider",
                "page": 4,
                "subchapters": {
                    "The Emotional Wellness of the Rider.": 6,
                    "Riding is a Sport.": 8,
                    "Learning/education.": 11,
                    "Visualization.": 13,
                    "Flow.": 15,
                    "Focus.": 16,
                    "Self-talk.": 18,
                    "Self-esteem/Self-discipline.": 19,
                    "Spiritual balance.": 20,
                    "Environment/Facilities.": 21,
                    "Goalsetting.": 21,
                    "The Physical Wellbeing of the Rider.": 28,
                    "Balance/Strength/Coordination.": 31,
                    "Agility/Body awareness.": 33,
                    "Nutrition/Rest.": 34,
                    "The Seat of the Rider.": 35,
                    "Physical Exercises for Riders.": 42,
                    "Stretches for Riders.": 49,
                },
            },
            {
                "num": 2,
                "name": "The Health of the Horse",
                "page": 55,
                "subchapters": {
                    "Accidents/Injuries.": 57,
                    "Worms.": 58,
                    "Lice.": 59,
                    "Colic.": 60,
                    "Urinary stone.": 62,
                    "Pastern dermatitis.": 62,
                    "Hoof laminitis.": 64,
                    "Spavin.": 66,
                    "Swelling of the suspensory ligament.": 67,
                },
            },
            {
                "num": 3,
                "name": "Legs – Mouth – Back",
                "page": 69,
                "subchapters": {
                    "Legs and leg construction of horses.": 69,
                    "Lower leg and hoof of the horse.": 72,
                    "The hoof.": 75,
                    "Shoeing.": 78,
                    "The mouth of the horse.": 84,
                    "The back of the horse.": 89,
                },
            },
            {
                "num": 4,
                "name": "Tack and its use",
                "page": 100,
                "subchapters": {
                    "The Saddle.": 101,
                    "Bridles and nosebands.": 108,
                    "Snaffle bits.": 110,
                    "Nosebands.": 114,
                    "Shank bits – The Icelandic Shank Bit.": 115,
                    "Reins.": 119,
                },
            },
            {
                "num": 5,
                "name": "Training Concepts – Training Levels",
                "page": 121,
                "subchapters": {
                    "Systematic Training.": 126,
                    "Physical balance.": 126,
                    "Physiological balance.": 130,
                    "Training levels.": 133,
                    "Even tempo – even steps.": 135,
                    "Contact – Coordination of the aids.": 138,
                    "Straight – Symmetrical.": 140,
                    "Flow of aids – Flexible.": 142,
                    "Suspension – Thrust – Power.": 145,
                    "Willingness – Energy – Lightness.": 147,
                    "Collected/Round.": 149,
                    "Speed.": 153,
                    "Hólar University Training Scale.": 155,
                },
            },
            {
                "num": 6,
                "name": "Exercises – Agility – Form",
                "page": 158,
                "subchapters": {
                    "Moving in and out on a circle.": 161,
                    "Giving the rein – Long rein.": 162,
                    "Leg Yield.": 164,
                    "Shoulder in.": 169,
                    "The half-halt.": 175,
                    "Form – Topline.": 180,
                    "Halt.": 183,
                    "Walking backwards – Backing.": 188,
                },
            },
        ],
        5: [
            {
                "num": 1,
                "name": "The Art and History of Riding",
                "page": 4,
                "subchapters": {
                    "The Role of the Horse.": 5,
                    "Alexander the Great.": 6,
                    "Xenophon.": 10,
                    "Classical Training. Period.": 11,
                    "The Renaissance Period.": 12,
                    "The Baroque Period.": 12,
                    "Francois Robichon de la Guériniére.": 13,
                    "Francois Baucher.": 16,
                    "Spanish Riding School.": 18,
                    "Gustave Steinbrecht.": 21,
                    "Federico Caprilli.": 22,
                    "Spanish Traditions.": 24,
                    "Nuno Olivera.": 26,
                    "The Twentieth Century.": 29,
                    "Throughout the Ages.": 31,
                },
            },
            {
                "num": 2,
                "page": 33,
                "name": "Lunging",
                "subchapters": {
                    "The Goals of Lunging.": 33,
                    "Lunging Equipment.": 34,
                    "Lunging Facilities and Environment.": 38,
                    "Lunging Methods.": 41,
                    "Rein Aids for Lunging.": 45,
                    "A Few Good Reasons to Lunge Horses.": 48,
                },
            },
            {
                "num": 3,
                "name": "Exercise Physiology of Horses",
                "page": 50,
                "subchapters": {
                    "Energy Metabolism in the Muscles of the Horse.": 51,
                    "Lactate Concentration in the Plasma.": 52,
                    "Aerobic and Anerobic Metabolism.": 53,
                    "The Relationship Between Exercise Intensity and Heart Rate.": 55,
                    "Purpose of Measuring Heart Rate in Horses.": 56,
                    "The Blood and Percentage of Red Blood Cells.": 57,
                    "Muscles and Types of Muscle Fibers.": 58,
                    "Horses are Elite Athletes.": 59,
                    "The Goals of Physical Training.": 60,
                    "Research in Horse Exercise Physiology.": 61,
                    "Professional Physical Structure of Training a Horse.": 63,
                    "The Training Pyramid.": 64,
                    "Effects of Training on Muscle.": 68,
                    "Effects of Training on the Respiratory System.": 69,
                    "Effects of Training on the Cardio-Vascular System.": 70,
                    "Effects of Training on the Musculoskeletal System.": 70,
                },
            },
            {
                "num": 4,
                "name": "Leading - Cooperation - Play",
                "page": 73,
                "subchapters": {"Work in Hand.": 74, "Leading Horses — Ponying.": 77},
            },
            {
                "num": 5,
                "name": "The Riding Arena",
                "page": 86,
                "subchapters": {"Riding Arenas.": 87, "Arena Training.": 90},
            },
            {
                "num": 6,
                "name": "Gaits",
                "page": 94,
                "subchapters": {
                    "Gait Training of Icelandic Horses.": 96,
                    "Gait Qualities.": 97,
                    "Definition of Gaits.": 100,
                    "Muybridge.": 101,
                    "From Trot to Pace.": 104,
                    "Key Factors in Gait Training.": 106,
                    "Gait transitions.": 106,
                    "Speed changes.": 107,
                    "Speed": 109,
                },
            },
            {
                "num": 7,
                "name": "Gait Training",
                "page": 111,
                "subchapters": {
                    "Walk": 112,
                    "Different Types of Walk.": 114,
                    "Ways to Improve the Walk.": 115,
                    "Trot.": 117,
                    "Trot Training.": 118,
                    "Ways to Improve Trot.": 123,
                    "Different Trots.": 123,
                    "Canter (Gallop).": 124,
                    "Canter Training.": 126,
                    "Ways to Improve Canter.": 130,
                    "Types of Canter.": 131,
                    "Tölt.": 132,
                    "Tölt Characteristics.": 133,
                    "Types of Tölt.": 135,
                    "Pace.": 142,
                    "Pace Aspects.": 143,
                    "Genotypes of Horses.": 144,
                    "Pace Training.": 150,
                    "Common Problems in Pace.": 152,
                },
            },
            {
                "num": 8,
                "page": 153,
                "name": "Competitions and Icelandic Horses",
                "subchapters": {
                    "Shows and Competitions.": 155,
                    "A Training Plan.": 158,
                    "Competition.": 162,
                },
            },
        ],
    }
